# (c) Infinite Networks <http://www.infinite.net.au>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    infinite_form.twig_extension.class: 'Infinite\FormBundle\Twig\FormExtension'

services:
    infinite_form.twig_extension:
        class: '%infinite_form.twig_extension.class%'
        tags:
            { name: 'twig.extension' }
